### ISSUE TITLE
Missing dependency recommonmark

### ISSUE THREAD

**Issue by iNLyze** [bfortuner/ml-cheatsheet#1]
@bfortuner, thanks for getting us organized to put this together. 
I cloned and installed the dependencies and found one to be missing: `recommonmark`
I am running the usual anaconda3 stack used in fast.ai/part2. 
Perhaps you could add this dependency to the install guide.  
`pip install recommonmark`

**Comment by bfortuner** [comment]
Thanks! Updated.
