### ISSUE TITLE
Tools for generating figures

### ISSUE THREAD

**Issue by xbainbain** [bfortuner/ml-cheatsheet#10]
Hey, I am currently working on section "Activation Functions". Since I want to keep the consistency of the figures of the function, could you note the tools that you use to generate them? 😄 @bfortuner

**Comment by bfortuner** [comment]
I believe it's this for graphing
https://www.desmos.com/calculator

And of course latex 
http://www.sphinx-doc.org/en/stable/ext/math.html

**Comment by xbainbain** [comment]
Okay, Thanks
