### ISSUE TITLE
Adding softmax activation function.

### ISSUE THREAD

**Issue by bhosalems** [bfortuner/ml-cheatsheet#20]
I liked the idea of the ml-cheatsheets to give a quick but concise overview of the concept. I would like to add the explanations for the softmax, Dying RELU problem. Is there any template I should follow?

**Comment by bfortuner** [comment]
Yes! You can add the code here:
https://github.com/bfortuner/ml-cheatsheet/blob/master/code/activation_functions.py

And the documentation here (formulas, explanation, graph):
https://github.com/bfortuner/ml-cheatsheet/blob/master/docs/activation_functions.rst

We typically include a graph created on Desmos, but if you're short for time. No worries.
https://www.desmos.com/calculator

**Comment by MaheshBhosale** [comment]
Sure, will do it on weekend.
