### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by janardhanpshetty** [bfortuner/ml-cheatsheet#3]
git clone https://github.com/bfortuner/ml-glossary
Error:
Cloning into 'ml-glossary'...
remote: Repository not found.
fatal: repository 'https://github.com/bfortuner/ml-glossary/' not found

**Comment by ivanistheone** [comment]
You probably want

    git clone https://github.com/bfortuner/ml-cheatsheet.git

(note the extra `.git` at the end of the URL, obtained from the [Clone or download] button on github)

**Comment by janardhanpshetty** [comment]
Yes I was able to correct that and do you suggest to commit to master directly ? instead of dev branch ?

**Comment by ivanistheone** [comment]
The best is to commit to a feature branch in your own repo, then open a pull request to `master` of `bfortuner/ml-cheatsheet`

**Comment by bfortuner** [comment]
Closing since it looks like you successfully created the request
