### ISSUE TITLE
Open a dev branch for committing

### ISSUE THREAD

**Issue by janardhanpshetty** [bfortuner/ml-cheatsheet#4]
Currently we have only master branch. We should have dev branch for the changes to be committed so that master is clean and production version.

**Comment by ivanistheone** [comment]
IMHO, the project is small enough that committing directly to `master` isn't going to be a problem.

You should fork the repo under your own github account, make commits in your fork and then open PRs to be merged into `bfortuner/ml-cheatsheet`.

Another best practices is to make individual changes in separate "feature branches" and then open small pull requests for each feature, e.g. 

```
# Fork repo to your github then 
cd MyProjects
git clone git@github.com:janardhanpshetty/ml-cheatsheet.git
cd ml-cheatsheet
git status
git checkout -b feature/docfix
# edit files
git add .
git commit -m"fixed something in doc"
git push
```
then github will automatically prompt you to open a PR from your branch `feature/docfix`.

**Comment by janardhanpshetty** [comment]
Tried to create a feature branch but it failed to access : 
git push --set-upstream origin feature/docfix
remote: Permission to bfortuner/ml-cheatsheet.git denied to janardhanpshetty.
fatal: unable to access 'https://github.com/bfortuner/ml-cheatsheet.git/': The requested URL returned error: 403

**Comment by ivanistheone** [comment]
You've cloned the `bfortuner/ml-cheatsheet.git` repo, which you are not allowed to "write to".

You'll need to start over the process. Note the URLs in the sample commands I sent you. Here are th steps. 

1. First you want to fork the `bfortuner/ml-cheatsheet` to obtain a clone of it under your own github account—use the [Fork] button and a 20 seconds later you'll have `janardhanpshetty/ml-cheatsheet` then run the commands:
```
cd MyProjects
mv ml-cheatsheet readonly-ml-cheatsheet
git clone git@github.com:janardhanpshetty/ml-cheatsheet.git
cd ml-cheatsheet
git status
git checkout -b feature/docfix
# edit files
git add .
git commit -m"fixed something in doc"
git push --set-upstream origin feature/docfix
```

Note I'm assuming you've setup an `ssh key` with github so you can use the `git+...` style URLs.
If this is not the case you have to change the URL in step 3 of the above code to the `https://` style:
```
git clone https://github.com/janardhanpshetty/ml-cheatsheet.git
```
After that every time you push, you'll be asked for your github username and password.

**Comment by janardhanpshetty** [comment]
@ivanistheone This helped thanks. Can you confirm on these steps for contribution ?

Fork brendan's repo

command line:
cd MyProjects
git clone git@github.com:janardhanpshetty/ml-cheatsheet.git
cd ml-cheatsheet
git status
git checkout -b feature/docfix
# edit files
git add .
git commit -m"fixed something in doc"
git push --set-upstream origin feature/docfix

# Collaborating
Create a pull request for my repo 
Merge pull request on my github then
Make html and check the changes for my master repo
Create a pull request from my master repo to brendan's repo
Add reviewers
Once reviewed brendan or other committer is able to merge the change 

One doubt is can we create a pull request from our feature branch directly to brendan's master branch without merging to our master, which is what is done currently ?

**Comment by ivanistheone** [comment]
Steps look good, and yes opening the PR from the feature branch (as you've done) is the way to do it.

**Comment by bfortuner** [comment]
Yep as Ivan said. No need to create separate branches. Just clone the repo. Make some changes, then create a pull request!
