### ISSUE TITLE
Derivative Rules and Integration formulas in Calculus Cheatsheet

### ISSUE THREAD

**Issue by davneet4u** [bfortuner/ml-cheatsheet#57]
Hey

I was going through the Calculas Cheatsheet here https://ml-cheatsheet.readthedocs.io/en/latest/calculus.html

Don't you think we should mention Integration Formulas, and Differentiation Rules as well?
Since its a cheat sheet, I think it would be useful for people to understand.

**Comment by bfortuner** [comment]
Yes we should! I got a job and haven't had much time lately to finish it. Open to PRs!

**Comment by davneet4u** [comment]
Hello Brendan,

I've created a PR adding the above mentioned formula sheets. Can you please have a look?
https://github.com/bfortuner/ml-cheatsheet/pull/60
